# DataSource Config
spring:
  session:
    timeout: 86400
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lemon
    password: root322R
    url: jdbc:mysql://119.29.204.26:3306/lemondb01


